# kube-linter configuration for Minted mUSD Canton
# Enforces K8s security best practices across all manifests
checks:
  # Include all default checks plus extras
  addAllBuiltIn: true
  exclude:
    # CronJob health-check uses busybox which runs as nobody (65534)
    # but linter may flag readOnlyRootFilesystem on init containers
    - "no-read-only-root-fs"
    # We use emptyDir for temp volumes in init containers — acceptable
    - "writable-host-mount"
    # Relay, bot, validators, and participant are singletons by design:
    # - Relay: duplicate instances cause duplicate attestation submissions
    # - Bot: duplicate instances cause duplicate liquidation attempts
    # - Validators: each is a unique identity (separate Deployment per validator)
    # - Participant: stateful — requires domain sequencer for HA, not replica scaling
    - "minimum-three-replicas"
