export const BORROW_MODULE_ABI = [
  "function interestRateBps() view returns (uint256)",
  "function minDebt() view returns (uint256)",
  "function totalDebt(address user) view returns (uint256)",
  "function healthFactor(address user) view returns (uint256)",
  "function maxBorrow(address user) view returns (uint256)",
  "function borrow(uint256 amount)",
  "function repay(uint256 amount)",
  "function withdrawCollateral(address token, uint256 amount)",
  "function reduceDebt(address user, uint256 amount)",
  "function setInterestRate(uint256 _rateBps)",
  "function setMinDebt(uint256 _minDebt)",
  "event Borrowed(address indexed user, uint256 amount, uint256 totalDebt)",
  "event Repaid(address indexed user, uint256 amount, uint256 remaining)",
  "event InterestAccrued(address indexed user, uint256 interest, uint256 totalDebt)",
  "event CollateralWithdrawn(address indexed user, address indexed token, uint256 amount)",
  "event InterestRateUpdated(uint256 oldRate, uint256 newRate)",
] as const;
