export const DIRECT_MINT_ABI = [
  "function usdc() view returns (address)",
  "function musd() view returns (address)",
  "function treasury() view returns (address)",
  "function mintFeeBps() view returns (uint256)",
  "function redeemFeeBps() view returns (uint256)",
  "function totalAccumulatedFees() view returns (uint256)",
  "function feeRecipient() view returns (address)",
  "function minMintAmount() view returns (uint256)",
  "function maxMintAmount() view returns (uint256)",
  "function minRedeemAmount() view returns (uint256)",
  "function maxRedeemAmount() view returns (uint256)",
  "function paused() view returns (bool)",
  "function mint(uint256 usdcAmount) returns (uint256)",
  "function redeem(uint256 musdAmount) returns (uint256)",
  "function previewMint(uint256 usdcAmount) view returns (uint256 musdOut, uint256 fee)",
  "function previewRedeem(uint256 musdAmount) view returns (uint256 usdcOut, uint256 fee)",
  "function remainingMintable() view returns (uint256)",
  "function availableForRedemption() view returns (uint256)",
  "function setFees(uint256 _mintFeeBps, uint256 _redeemFeeBps)",
  "function setLimits(uint256 _minMint, uint256 _maxMint, uint256 _minRedeem, uint256 _maxRedeem)",
  "function setFeeRecipient(address _recipient)",
  "function withdrawFees()",
  "function pause()",
  "function unpause()",
  "function recoverToken(address token, uint256 amount)",
  "event Minted(address indexed user, uint256 usdcIn, uint256 musdOut, uint256 fee)",
  "event Redeemed(address indexed user, uint256 musdIn, uint256 usdcOut, uint256 fee)",
  "event FeesWithdrawn(address indexed to, uint256 amount)",
  "event FeesUpdated(uint256 mintFeeBps, uint256 redeemFeeBps)",
  "event LimitsUpdated(uint256 minMint, uint256 maxMint, uint256 minRedeem, uint256 maxRedeem)",
] as const;
