export const MUSD_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function supplyCap() view returns (uint256)",
  "function isBlacklisted(address) view returns (bool)",
  "function hasRole(bytes32 role, address account) view returns (bool)",
  "function mint(address to, uint256 amount)",
  "function burn(address from, uint256 amount)",
  "function setSupplyCap(uint256 _cap)",
  "function setBlacklist(address account, bool status)",
  "event SupplyCapUpdated(uint256 oldCap, uint256 newCap)",
  "event BlacklistUpdated(address indexed account, bool status)",
  "event Mint(address indexed to, uint256 amount)",
  "event Burn(address indexed from, uint256 amount)",
] as const;
