// Updated to TreasuryV2 ABI (was stale v1 with non-existent functions)
export const TREASURY_ABI = [
  // View functions
  "function totalValue() view returns (uint256)",
  "function totalValueNet() view returns (uint256)",
  "function reserveBalance() view returns (uint256)",
  "function targetReserve() view returns (uint256)",
  "function totalBacking() view returns (uint256)",
  "function availableReserves() view returns (uint256)",
  "function strategyCount() view returns (uint256)",
  "function getAllStrategies() view returns (tuple(address strategy, uint256 targetBps, uint256 minBps, uint256 maxBps, bool active, bool autoAllocate)[])",
  "function getCurrentAllocations() view returns (address[] strategyAddresses, uint256[] currentBps, uint256[] targetBps)",
  "function pendingFees() view returns (uint256)",
  "function reserveBps() view returns (uint256)",
  "function asset() view returns (address)",
  "function vault() view returns (address)",
  "function fees() view returns (uint256 performanceFeeBps, uint256 accruedFees, address feeRecipient)",
  // Vault interface
  "function deposit(address from, uint256 amount)",
  "function withdraw(address to, uint256 amount)",
  "function depositFromVault(uint256 amount) returns (uint256[])",
  "function withdrawToVault(uint256 amount) returns (uint256)",
  // Admin functions
  "function addStrategy(address strategy, uint256 targetBps, uint256 minBps, uint256 maxBps, bool autoAllocate)",
  "function removeStrategy(address strategy)",
  "function updateStrategy(address strategy, uint256 newTargetBps, uint256 newMinBps, uint256 newMaxBps, bool autoAllocate)",
  "function rebalance()",
  "function accrueFees()",
  "function claimFees()",
  "function setFeeConfig(uint256 performanceFeeBps, address feeRecipient)",
  "function setReserveBps(uint256 _reserveBps)",
  "function setMinAutoAllocate(uint256 _minAmount)",
  "function setVault(address _vault)",
  "function recoverToken(address token, uint256 amount)",
  "function emergencyWithdrawAll()",
  "function pause()",
  "function unpause()",
  // Events
  "event Deposited(address indexed from, uint256 amount, uint256[] allocations)",
  "event Withdrawn(address indexed to, uint256 amount)",
  "event StrategyAdded(address indexed strategy, uint256 targetBps)",
  "event StrategyRemoved(address indexed strategy)",
  "event StrategyUpdated(address indexed strategy, uint256 newTargetBps)",
  "event StrategyWithdrawn(address indexed strategy, uint256 amount)",
  "event FeesAccrued(uint256 yield_, uint256 protocolFee)",
  "event FeesClaimed(address indexed recipient, uint256 amount)",
  "event Rebalanced(uint256 totalValue)",
  "event EmergencyWithdraw(uint256 amount)",
] as const;
